# Тема 10. Декораторы и исключения.
Отчет по Теме #10 выполнил(а):
- Сергеева Кристина Алексеевна 
- ИНО ЗБ ПОАС-22-1

| Задание |  Сам_раб |
| ------ |  ------ |
| Задание 1 | + |
| Задание 2 | + |
| Задание 3 | + | 
| Задание 4 | + | 
| Задание 5 | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. 

```python
import time
def calculate_execution_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Время выполнения функции '{func.__name__}': {execution_time:.6f} секунд")
        return result
    return wrapper
@calculate_execution_time
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2)
if __name__ == '__main__':
    fibonacci()
    print()
```
### Результат.
![Меню]().


## Выводы

Все условия задания выполнены!

## Самостоятельная работа №2
### Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. 

```python
try:
    # Чтение из пустого файла
    with open("empty.txt", "r") as file:
        data = file.read()
        if not data:
            raise Exception("Файл пустой")
        print("Данные из файла 'empty.txt':")
        print(data)
except Exception as e:
    print("Ошибка:", e)
print()

try:
    # Чтение из файла с информацией
    with open("data.txt", "r") as file:
        data = file.read()
        if not data:
            raise Exception("Файл пустой")
        print("Данные из файла 'data.txt':")
        print(data)
except Exception as e:
    print("Ошибка:", e)

```
### Результат.
![Меню]().

## Выводы

Все условия задания выполнены!
  
## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка "Неподходящий тип данных. Ожидалось число."

```python
def add_two_to_input():
    try:
        user_input = input("Введите число: ")
        number = int(user_input)
        result = 2 + number
        print("Результат сложения: ", result)
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

# Тесты
# Входные данные - число
add_two_to_input()

# Входные данные - строка
add_two_to_input()


```
### Результат.
![Меню]().

## Выводы

Все условия задания выполнены!
  
## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций.

```python
# класс декоратора
class ValidateInput:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        for arg in args:
            if not isinstance(arg, (int, float)):
                print("Ошибка: Неподходящий тип данных. Ожидалось число.")
                return None
        return self.func(*args, **kwargs)
# Функция, умножающая число на 5
@ValidateInput
def multiply_by_two(num):
    return num * 5
# Функция, делящая число на 5
@ValidateInput
def divide_by_two(num):
    return num / 5
# Тесты
print("Умножение на 5:", multiply_by_two(13))
print("Деление на 5:", divide_by_two("10"))
```
### Результат.
![Меню]().

## Выводы

Для данной задачи создан декоратор validate_input, который будет проверять корректность входных данных для функций. Декоратор будет использоваться для двух функций: одна будет умножать число на 5, а другая будет проводить деление числа на 5. 
  
## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. 


```python
# исключение NegativeValueError
class NegativeValueError(Exception):
    def __init__(self, value):
        self.value = value
        super().__init__(f"Отрицательное число {value} ")

# Фрагмент кода 1: Функция, которая принимает число и выбрасывает исключение, если число отрицательное
def number(num):
    if num < 0:
        raise NegativeValueError(num)
    else:
        return num
# Фрагмент кода 2: Проверка двух чисел с использованием исключения
try:
    a = number(10)
    print(f"Число A: {a}")
    b = number(-5)
    print(f"Число B: {b}")
except NegativeValueError as e:
    print(f"Ошибка: {e}")


```
### Результат.
![Меню]().

## Выводы
Было создано исключение NegativeValueError, которое работает при попытке передачи отрицательного значения в функции. Далее в двух фрагментах кода используется это исключение. 

## Общие выводы по теме
Декораторы в Python предоставляют простой и элегантный способ добавления функциональностик существующим функциям или классам. Исключения позволяют программистам обрабатывать ошибки и справляться с исключительными ситуациями, такими как деление на ноль, обращениек несуществующему индексу списка, открытие несуществующего файла и т.д., чтобы предотвратить аварийное завершение программы.
